// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrKMzQ7ZJPTKaHF5O1mIahE17s5YbPtGA',
    appId: '1:161519485763:web:8efc17f0bdd1685081a5f6',
    messagingSenderId: '161519485763',
    projectId: 'fir-exam-3d77b',
    authDomain: 'fir-exam-3d77b.firebaseapp.com',
    storageBucket: 'fir-exam-3d77b.appspot.com',
    measurementId: 'G-CPLLSV1BLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXWBe7i5EEFfqQVJWDxkrWdW7f3T0BaQ',
    appId: '1:161519485763:android:779072ab28e7afcc81a5f6',
    messagingSenderId: '161519485763',
    projectId: 'fir-exam-3d77b',
    storageBucket: 'fir-exam-3d77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWDRXZWTgR2N_kmoTXd19gsVSYG_dXbM',
    appId: '1:161519485763:ios:763dccf158165a8381a5f6',
    messagingSenderId: '161519485763',
    projectId: 'fir-exam-3d77b',
    storageBucket: 'fir-exam-3d77b.appspot.com',
    iosBundleId: 'com.example.whiztec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWDRXZWTgR2N_kmoTXd19gsVSYG_dXbM',
    appId: '1:161519485763:ios:763dccf158165a8381a5f6',
    messagingSenderId: '161519485763',
    projectId: 'fir-exam-3d77b',
    storageBucket: 'fir-exam-3d77b.appspot.com',
    iosBundleId: 'com.example.whiztec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4OgHkAZ-JsTXjHCWCWS9tHC6oPrT0x3s',
    appId: '1:161519485763:web:48fa89c73af58f3581a5f6',
    messagingSenderId: '161519485763',
    projectId: 'fir-exam-3d77b',
    authDomain: 'fir-exam-3d77b.firebaseapp.com',
    storageBucket: 'fir-exam-3d77b.appspot.com',
    measurementId: 'G-ERDS7394YR',
  );
}
